apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: hydeenoble/kubia
    name: kubia
    ports: 
    - containerPort: 8085
      protocol: TCP