apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia-rs
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: kubia-rs
  template:
    metadata: 
      labels:
        app: kubia-rs
    spec:
      containers:
      - name: kubia
        image: hydeenoble/kubia
